### ISSUE TITLE
PM shows other name name for both sent and received messages

### ISSUE THREAD

**Issue by mdmower** [tilal6991/HoloIRC#90]
Private messages show the name of the other person for both sent and received messages. See here: http://i.imgur.com/oSqxEvv.png

**Comment by mdmower** [comment]
Seems to be an abandoned project. The fix from maniac103 works, but no new versions of HoloIRC are being rolled for release on the Play store. I've moved onto qicr.

**Comment by maniac103** [comment]
@mdmower I've unsucessfully nagged @tilal6991 to do a new release from the existing code :-( I can upload an apk off my repo though if you (or anyone else) are/is interested. Due to using the new appcompat libraries it doesn't look as outdated anymore, and I did other fixes (like proper notifications for Wear) as well.

**Comment by SolarAquarion** [comment]
Sure I guess

**Comment by tilal6991** [comment]
I've been persuaded to release a new version which I will do when everything is merged.
